#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("br.com.weblayer.venda.android.Resource", IsApplication=true)]

namespace br.com.weblayer.venda.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_AddProduct = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_ajuda = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_configuracoes = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_deletarproduto = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_salvar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int search = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050020
			public const int action_AddProduct = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int action_ajuda = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int action_configuracoes = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int action_deletarproduto = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int action_salvarproduto = 2131034140;
			
			// aapt resource value: 0x7f050004
			public const int checkBox_Tema1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int checkBox_Tema2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int checkBox_Tema3 = 2131034118;
			
			// aapt resource value: 0x7f050015
			public const int edtInformarFiltro = 2131034133;
			
			// aapt resource value: 0x7f05000b
			public const int lblCodigo = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int lblNome = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int lblTabelaPrecos = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int lblUnidadeMedida = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int listViewProdutos = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int listviewHome = 2131034131;
			
			// aapt resource value: 0x7f050001
			public const int relativeLayoutBase = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int txtAjuda = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtClientes = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int txtCodigo = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int txtCodigoProduto = 2131034136;
			
			// aapt resource value: 0x7f05000e
			public const int txtNome = 2131034126;
			
			// aapt resource value: 0x7f050019
			public const int txtNomeProduto = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int txtPedidos = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int txtPrecos = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int txtTabelaPrecos = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int txtTblPrecoProduto = 2131034139;
			
			// aapt resource value: 0x7f050008
			public const int txtTema1Teste = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int txtTema2Teste = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int txtTema3Teste = 2131034122;
			
			// aapt resource value: 0x7f05001a
			public const int txtUniMedidaProduto = 2131034138;
			
			// aapt resource value: 0x7f050010
			public const int txtUnidadeMedida = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int txtVersaoApp = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Ajuda = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_Base = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_Clientes = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Activity_Configuracoes = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Activity_EditarProduto = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Activity_Home = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Activity_Pedidos = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Activity_Produtos = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Activity_TabelaPrecos = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Adapter_Produtos_ListView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Botoes_EditarProduto = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Botoes_Home = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Botoes_Produtos = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int TextoTeste = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
