#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("br.com.weblayer.venda.android.Resource", IsApplication=true)]

namespace br.com.weblayer.venda.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int unidades_medida = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_AddProduct = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_ajuda = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_configuracoes = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_deletarproduto = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_salvar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int search = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06003f
			public const int action_AddProduct = 2131099711;
			
			// aapt resource value: 0x7f06003e
			public const int action_ajuda = 2131099710;
			
			// aapt resource value: 0x7f06003d
			public const int action_configuracoes = 2131099709;
			
			// aapt resource value: 0x7f06003c
			public const int action_deletar = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int action_salvar = 2131099707;
			
			// aapt resource value: 0x7f060031
			public const int btnAdicionar = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int btnFinalizar = 2131099698;
			
			// aapt resource value: 0x7f060005
			public const int checkBox_Tema1 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int checkBox_Tema2 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int checkBox_Tema3 = 2131099655;
			
			// aapt resource value: 0x7f060033
			public const int edtInformarFiltro = 2131099699;
			
			// aapt resource value: 0x7f060040
			public const int item1 = 2131099712;
			
			// aapt resource value: 0x7f060012
			public const int lblCNPJ = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int lblCodigo = 2131099668;
			
			// aapt resource value: 0x7f06000c
			public const int lblCodigoCliente = 2131099660;
			
			// aapt resource value: 0x7f060025
			public const int lblCodigoPedido = 2131099685;
			
			// aapt resource value: 0x7f06001c
			public const int lblCodigoTabelaPreco = 2131099676;
			
			// aapt resource value: 0x7f06002d
			public const int lblDataEmissao = 2131099693;
			
			// aapt resource value: 0x7f060022
			public const int lblDescontoMaxTabelaPreco = 2131099682;
			
			// aapt resource value: 0x7f06001e
			public const int lblDescricaoTabelaPreco = 2131099678;
			
			// aapt resource value: 0x7f060027
			public const int lblIdCliente = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int lblIdVendedor = 2131099689;
			
			// aapt resource value: 0x7f060016
			public const int lblNome = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int lblNomeFantasia = 2131099664;
			
			// aapt resource value: 0x7f06002f
			public const int lblObservacao = 2131099695;
			
			// aapt resource value: 0x7f06000e
			public const int lblRazaoSocial = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int lblTabelaPrecos = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int lblUnidadeMedida = 2131099672;
			
			// aapt resource value: 0x7f060020
			public const int lblValorTabelaPreco = 2131099680;
			
			// aapt resource value: 0x7f06002b
			public const int lblValorTotal = 2131099691;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060034
			public const int listViewProdutos = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int listViewTabelaPrecos = 2131099702;
			
			// aapt resource value: 0x7f060024
			public const int listviewHome = 2131099684;
			
			// aapt resource value: 0x7f060003
			public const int lstViewCliente = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int relativeLayoutBase = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int spinnerUnidadeMedida = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int txtAjuda = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int txtCNPJ = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int txtClientes = 2131099650;
			
			// aapt resource value: 0x7f060015
			public const int txtCodigo = 2131099669;
			
			// aapt resource value: 0x7f06000d
			public const int txtCodigoCliente = 2131099661;
			
			// aapt resource value: 0x7f060026
			public const int txtCodigoPedido = 2131099686;
			
			// aapt resource value: 0x7f060037
			public const int txtCodigoProduto = 2131099703;
			
			// aapt resource value: 0x7f06001d
			public const int txtCodigoTabelaPreco = 2131099677;
			
			// aapt resource value: 0x7f06002e
			public const int txtDataEmissao = 2131099694;
			
			// aapt resource value: 0x7f060023
			public const int txtDescontoMaxTabelaPreco = 2131099683;
			
			// aapt resource value: 0x7f06001f
			public const int txtDescricaoTabelaPreco = 2131099679;
			
			// aapt resource value: 0x7f060028
			public const int txtIdCliente = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int txtIdvendedor = 2131099690;
			
			// aapt resource value: 0x7f060017
			public const int txtNome = 2131099671;
			
			// aapt resource value: 0x7f060011
			public const int txtNomeFantasia = 2131099665;
			
			// aapt resource value: 0x7f060038
			public const int txtNomeProduto = 2131099704;
			
			// aapt resource value: 0x7f060030
			public const int txtObservacao = 2131099696;
			
			// aapt resource value: 0x7f060035
			public const int txtPrecos = 2131099701;
			
			// aapt resource value: 0x7f06000f
			public const int txtRazaoSocial = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int txtTabelaPrecos = 2131099675;
			
			// aapt resource value: 0x7f06003a
			public const int txtTblPrecoProduto = 2131099706;
			
			// aapt resource value: 0x7f060009
			public const int txtTema1Teste = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int txtTema2Teste = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int txtTema3Teste = 2131099659;
			
			// aapt resource value: 0x7f060039
			public const int txtUniMedidaProduto = 2131099705;
			
			// aapt resource value: 0x7f060021
			public const int txtValorTabelaPreco = 2131099681;
			
			// aapt resource value: 0x7f06002c
			public const int txtValorTotal = 2131099692;
			
			// aapt resource value: 0x7f060008
			public const int txtVersaoApp = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Ajuda = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_Base = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_Clientes = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Activity_Configuracoes = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Activity_EditarClientes = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Activity_EditarProduto = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Activity_EditarTabelaPreco = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Activity_Home = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Activity_PedidoItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Activity_Pedidos = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Activity_Produtos = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Activity_TabelaPrecos = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Adapter_Clientes_ListView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Adapter_Produtos_ListView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Adapter_TabelaPreco_ListView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Botoes_Editar = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Botoes_Home = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Botoes_InserirNovo = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SpinnerListAdapter = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int TextoTeste = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
